################################################################################
- name: Run a module from inside a collection
  hosts: localhost
  tasks:
    - name: Gather some real Facts.
      myfirst.test_collection.real_facts:
        name: John Snow
      register: testout
    - debug:
        msg: "{{ testout }}"

################################################################################
- name: Run a module from inside a collection using the collections keyword
  hosts: localhost
  collections:
    - myfirst.test_collection
  tasks:
    - name: Gather some real Facts.
      real_facts:
        name: Jane Doe
      register: testout
    - debug:
        msg: "{{ testout }}"

################################################################################
- name: Run a role from inside of a collection
  hosts: localhost
  roles:
    - "myfirst.test_collection.factoid"
