---

- hosts: mywebservers

  vars: 
   - MyMessage: {{ line1 }}
   - DBMessage: {{ line2 }}

  tasks:
   - name: index.html copy
     template: src=/home/centos/index.html.j2 dest=/var/www/html/index.html
     become: yes
