---
- name: Using ServiceNow Collection
  hosts: localhost
  gather_facts: no

  tasks:
  - debug: msg="Debug message {{username}}"
  - debug: msg="Debug message memory {{cpu}}"
  - debug: msg="Debug message cpu {{memory}}"
  - name: Create an incident
    servicenow.servicenow.snow_record:
      username: admin
      password: llDpE4MZ6thQ
      instance: dev76820
      state: present
      data:
        short_description: "BEFORE --- The product was ordered by {{username}}"
        severity: 3
        priority: 2
